#!/bin/bash

set -e

export RAILS_ENV=${RAILS_ENV:=staging}
export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:=us-east-1}
export CLOUDFORMATION_BUCKET=${CLOUDFORMATION_BUCKET:="mycfbucket.custominktech.$(whoami).${AWS_DEFAULT_REGION}"}

aws cloudformation deploy \
  --region ${AWS_DEFAULT_REGION} \
  --template-file "ops/s3/template.yaml" \
  --stack-name "rails-assets-s3-${RAILS_ENV}" \
  --s3-bucket "$CLOUDFORMATION_BUCKET" \
  --s3-prefix "rails-assets-s3-${RAILS_ENV}" \
  --capabilities "CAPABILITY_IAM" \
  --tags \
    "env=${RAILS_ENV}" \
    "group=ecommerce" \
    "application=rails-assets" \
  --parameter-overrides \
    RailsEnv="$RAILS_ENV"
